### ISSUE TITLE
Select stream quality

### ISSUE THREAD

**Issue by jbaconbits** [TwitchedApp/Twitched#1]
### Description
Currently, it doesn't appear that streams actually ever ramp up to Source quality for streams (I haven't seen anything hit 1080p60. Would it be possible to add a setting to select the default stream quality?

**Roku Model:** 

Primere+ 

**Roku Firmware Version:** 
8.1

**Twitched Version:**
1.0

**Comment by rolandoislas** [comment]
Streams have been temporarily limited to 30 FPS to address an issue with first generation Roku TVs.. Twitched version 1.1 is publishing and will re-enable 60 FPS streams.

**Comment by rolandoislas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resolution/Bitrate Selection](https://trello.com/c/q7MlDhNY/22-resolution-bitrate-selection)

**Comment by rolandoislas** [comment]
Added in v1.2.
