### ISSUE TITLE
Cannot link account to Twitched

### ISSUE THREAD

**Issue by narcogen** [TwitchedApp/Twitched#17]
### Description
Been using Twitched successfully now for some time.

Open for the first time today and the Followed channel list is empty. Instead is an instruction to link an account.

### Steps to Reproduce
1. Followed the instructions and re-linked the account. Received success message.

2. Once the message is dismissed, the Followed list again appears empty with the message "Press OK on your Roku remote to begin linking a Twitch account."

3. You can link an account several times, but after each "successful" attempt, the Followed list is empty and the instruction  repeats again.

**Expected behavior:** Expected to see my list of followed channels after linking.

**Actual behavior:** Followed list is empty, instructions to link appear again.

**Roku Model:** 4660X Roku Ultra

**Roku Firmware Version:** 8.0.1 build 4090-46

**Twitched Version:** Version 1.3 build 1908

### Additional Information
[Any other information related to the problem]

**Comment by rolandoislas** [comment]
The following is a workaround until an update can be released to patch the bug:


1. Link an account normally. A dialog will show the message, "A Twitch account has been linked."
2. Wait 5-10 seconds.
3. Exit the app by pressing the home button on the remote.

On the next launch, the account linking should work correctly.

**Comment by rolandoislas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Account Linking Fails after Invalidating Token](https://trello.com/c/vWrIA7XQ/47-account-linking-fails-after-invalidating-token)

**Comment by narcogen** [comment]
Made another attempt and linking worked. I may have done the above almost by accident while attempting to make linking work earlier.
