### ISSUE TITLE
Not seeing some followed streams under Following

### ISSUE THREAD

**Issue by danviterise** [TwitchedApp/Twitched#19]
### Description
There are certain streams I never see on the Followed screen even though I follow them. If I search for the stream or the game that streamer is playing, I can find the stream. This is happening to the same streamers; some streams I always see under followed and some I never see. These are not newly followed streams, it's a mix of streams I've been following for a while and some recently.

### Steps to Reproduce
1. Open Followed screen
2. Not all followed streams visible

**Expected behavior:** [What was supposed to happen]
All followed streams appear on Followed page

**Actual behavior:** [What actually happened]
Only certain streams appear on Followed screen and some never appear

**Roku Model:** [Model]
Roku Premiere - 4620X

**Roku Firmware Version:** [Firmware version] 
8.0.1 Build 4090

**Twitched Version:** [Version number]
1.4 Build 2430

**Comment by K0RP53** [comment]
This may be related to my post FYI

**Comment by rolandoislas** [comment]
Possibly related to #21.

**Comment by rolandoislas** [comment]
@danviterise would you mind posting your Twitch username? If you prefer, you may send it to support@twitched.org.

Does the error occur on the Twitched v1.5 beta: https://my.roku.com/add/Q2M6C6

**Comment by K0RP53** [comment]
How do you add the beta? Using link just sends me to the regular release (1.4). At least I think it's 1.4 because I added it and checked updates on roku player but didn't work. Still 1.4

**Comment by danviterise** [comment]
My Twitch username is LittleShortDude16

Do I have to pay to use the beta? It seems like it is trying to charge me for another channel. I already have the paid version.

**Comment by K0RP53** [comment]
It didn't charge me even though I said yes. Not sure why it says a price.

**Comment by rolandoislas** [comment]
If the account owns Twitched, there will be no charge.

**Comment by danviterise** [comment]
Seems *better* on the beta. 3 streams weren't showing on 1.4. On 1.5, 2 of the missing ones were now showing but 1 was still missing.
