### ISSUE TITLE
Followed Streams Fail to Load

### ISSUE THREAD

**Issue by Timnus** [TwitchedApp/Twitched#2]
### Description
get error Failed to connect  to the API server
Error code: 1005

### Steps to Reproduce
1. [First step]
goto twitched channel in Roku
2. [Second step]
highlight followed
...

**Expected behavior:** [What was supposed to happen]
show top 100 active followed channels

**Actual behavior:** [What actually happened]
get error and no list

**Roku Model:** [Model]
rc182

**Roku Firmware Version:** [Firmware version] 
v.2.01.19.062

**Twitched Version:** [Version number]
unable to locate in Roku

### Additional Information
[Any other information related to the problem]
 found this on account screen
3800X streaming stick
SW 8.0.1 - Bld 4042-55
ct37ae215989

**Comment by rolandoislas** [comment]
# Potential Resolutions

- Try to access the followed menu again. The API may have been down temporarily.
- Log out and log in again from the Twitched setting menu.
- Send your Twitch user name to support@twitched.org.

**Comment by bodyslam911** [comment]
I have the same problem but I have Roku Premiere with the latest update.

**Comment by rolandoislas** [comment]
Fix applied.

**Comment by rolandoislas** [comment]
Accounts with over 300 followed channels will now properly load.
