### ISSUE TITLE
Previous search keywords

### ISSUE THREAD

**Issue by K0RP53** [TwitchedApp/Twitched#20]
It would be great if the roku search section had the previous search keywords selectable like the official app for roku had. This makes it much easier to pick something you've searched for already than having to type it out everytime if your using the remote.

**Comment by K0RP53** [comment]
It also appears that if a stream is in subscriber only mode, you can't search for their channel or see it in the "followed" section. Or share it with twitched Android app. You may already be aware of this fact.

**Comment by rolandoislas** [comment]
Would you mind submitting a new bug report for the subscriber mode error? Also, could you provide example channels that this issue occurs with?

**Comment by rolandoislas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Search History](https://trello.com/c/xh4vz5a9/52-search-history)

**Comment by rolandoislas** [comment]
This has been added in the latest beta build.
