### ISSUE TITLE
Stream offline even though it’s live

### ISSUE THREAD

**Issue by sc0o8i3** [TwitchedApp/Twitched#22]
### Stream offline even though it’s currently live
I tried using Twitched Zero and was streaming Ninja playing Fortnite. It worked fine and thought I’ll pay for the app and tried streaming Ninja again but it popped up with a message stating the stream was offline. I verified on my mobile to ensure the stream was still on and it was definitely on.

### Steps to Reproduce
1. Launch Twitched app (paid version)
2. Chose Ninja stream (from ‘popular’ category)
3. Window pops up stating the stream is offline (Error Code: -3)
4. Even attempted to choose Games>Fortnite>Ninja’s stream and received same error code and message

**Expected behavior:** [Stream should load]

*Actual behavior:** [Window with error message pops up stating stream is offline]

**Roku Model:** [TCL Roku TV 5106X]

**Roku Firmware Version:** [Since it’s a TV model, software build: 4183-08] 

**Twitched Version:** [Whatever version is available off the Roku store (6/2/18)]

### Additional Information
[Any other information related to the problem]

**Comment by rolandoislas** [comment]
Had the stream gone live recently? Twitch's API has a three-minute delay due to caching.

**Comment by sc0o8i3** [comment]
I’ll try streaming again, but to answer your question. No, the stream had been on for over an hour by the time I downloaded the app and attempted to stream the channel.

**Comment by cell-tech10** [comment]
I am also having this problem. Not just Ninja's channel, but several other Fortnite players. In addition, when the stream does load certain channels are choppy and extremely poor resolution. When i go to different streamers they work fine, some in fortnite and some in different games; it appears random. A week ago this app was flawless, not sure what changed.

**Comment by rolandoislas** [comment]
@cell-tech10 Did the fix from #23 resolve this for you?

**Comment by cell-tech10** [comment]
@rolandoislas i have had no issues with this since that fix, no. 

I do think that the 30 fps is noticeable, getting 60hz back one day would be excellent, but right now things are stable and functioning and I am happy.

**Comment by Scootertaj** [comment]
I'm also experiencing this issue with my Roku 3500x streaming stick. #23 did not resolve it for me.

**Comment by rolandoislas** [comment]
I have not been able to reproduce the issue. The Twitched [v1.5 beta](https://my.roku.com/add/Q2M6C6) adds local stream handling that may resolve the issue.

**Comment by Scootertaj** [comment]
I'm still experiencing this issue with JUST Ninja's stream. Now it's giving me "Error code: -1" (previously -3)

**Comment by cell-tech10** [comment]
@rolandoislas  how do you get v1.5 on roku?? i cannot seem to update it

**Comment by Dsteblen** [comment]
Having the same issue. Just purchased the app (6/29/18) can’t watch half of the streamers and get error code -3. Tried the fixes didn’t work. I know the streams are online because my phone twitch app has them no problem. Please help.

**Comment by rolandoislas** [comment]
@Dsteblen please post the model of Roku, its firmware version, and the Twitched version in use.

**Comment by Dsteblen** [comment]
Roku Model #: 55S405
Roku version 4.2.9.4
 I resolved the issue myself. Appreciate the quick response greatly!

**Comment by DaveKenroy** [comment]
I'm having the same issue. I purchased the Twitched app, but whenever I try to add beta v1.5, it adds v1.4 instead.

Roku model: 4640X
Roku version: 8.1.0 Build 4137

**Comment by K0RP53** [comment]
Try scrolling up. I thought this to until I realized the app was at the bottom of the list. It doesn't replace existing one.

**Comment by DaveKenroy** [comment]
I delete the Twitched app from Roku and when using the link, it adds Twitched back, but it's still v1.4.

**Comment by K0RP53** [comment]
I'd just leave the original there and try adding the beta.

**Comment by DaveKenroy** [comment]
I tried that as well, but no new version ever shows up.

**Comment by K0RP53** [comment]
Only other suggestion I have is to make absolutely sure you're using the right link.

**Comment by DaveKenroy** [comment]
I've used the (same) link in multiple of his posts pointing to v1.5 beta, including the only one in this thread.

**Comment by DaveKenroy** [comment]
Thank you for responding. After a while my Roku locked up and crashed a few times. After the second lock up and reboot the app finally showed up and promptly locked up again. One more reboot and the app appeared with no more lock ups or crashes.
