### ISSUE TITLE
Very choppy Fortnite streams

### ISSUE THREAD

**Issue by cell-tech10** [TwitchedApp/Twitched#23]
**Describe the bug**
Certain (seemingly random) streams are extremely choppy with low resolution, completely unwatchable. 

**To Reproduce**
1) Go to any Fortnite stream (first noticed while watching Ninja)
2) Load said stream. 

**Expected behavior**
I expect that I can watch the stream without difficulty. 

**Screenshots**

Current most recent Roku and Twitched app.

**Comment by rolandoislas** [comment]
Does the issue appear after specifying a resolution in Twitched's settings?

**Comment by cell-tech10** [comment]
@rolandoislas  even when set to automatic, it does this. I want to be clear - this is not buffering. I have used this app with a poor connection where it constantly stops to buffer and this is not the same. Instead the channel is just extremely choppy with constant microstutters. 

I will note that the stuttering stops when I drop it to 480p (which is awful...), but oddly enough on certain channels that work without any issue I can leave it on 1080p and its flawless. I do not suspect it is a connection issue based on this discrepancy.

**Comment by rolandoislas** [comment]
Please provide the Roku model number.

**Comment by cell-tech10** [comment]
@rolandoislas  2017 streaming stick model 3800r

**Comment by rolandoislas** [comment]
Some Roku models have had trouble with the 60 FPS video format from Twitch. I have limited the 3800X to 30 FPS to determine if that is the issue.

**Comment by cell-tech10** [comment]
@rolandoislas  well the resolution doesnt look as sharp as it used to (even when set to 1080p), but the choppyness is resolved so I am happy about that.

Thank you for the response.  I will let you know if the stuttering resumes.
