### ISSUE TITLE
Stuck on Receiving screen

### ISSUE THREAD

**Issue by hipolymereraser** [TwitchedApp/Twitched#27]
### Description
When trying to watch Ninja's stream, it gets stuck on the receiving screen and never loads. I can watch anyone elses stream, just not his.

### Steps to Reproduce
It happens every time I try to play it.

I tried deleting the app, restarting my roku, changing the quality, twitched zero and none of that helped.
**Expected behavior:** It should load and play his stream.

**Actual behavior:** I push play and it looks like it's going to load, only says receiving, but the bar never loads and the stream never plays.

**Roku Model:** 4210x-Roku2

**Roku Firmware Version:** 8.0.0 build 4184-04

**Twitched Version:** Not sure how to check that.

### Additional Information
The only thing I noticed that was different from the other streams was his name isn't showing up under streamer. On the regular Twitch app, his stream plays fine.

**Comment by cell-tech10** [comment]
I am having the SAME EXACT PROBLEM! why is it *always* ninja's stream with issues. its like a conspiracy or something. 

one of the guys was super responsive to me last week, hopefully he will show up again!

**Comment by cell-tech10** [comment]
Interestingly, this is not an issue on the 1.5 beta version!

**Comment by hipolymereraser** [comment]
It’s working now! Thank you!

**Comment by hipolymereraser** [comment]
Now it keeps saying a -3 error for Ninja and a few others.

**Comment by CDProjectRed** [comment]
its not working, keep freezing as well

**Comment by shea1337** [comment]
Also getting a -3 error on any stream.... I could watch a few minutes of SGDQ stream before it went offline with a -3. Restarted my roku tv and everything, still -3
