### ISSUE TITLE
Failed to connect to the API server (v1.5 beta)

### ISSUE THREAD

**Issue by Scootertaj** [TwitchedApp/Twitched#28]
**Describe the bug**
Upon opening the channel, I receive 'Failed to connect to the API server. Error code: 1005'. Thus, can't watch any stream.

**To Reproduce**
1. Open Twitched channel v1.5 beta

**Expected behavior**
Twitch streams would load

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Roku (please complete the following information):**
 - Roku Model: 3500x
 - Twitched Version: Twitched v1.5 beta

**Comment by rolandoislas** [comment]
The Twitched staging (beta) server was down momentarily.
