### ISSUE TITLE
60fps streams freeze, drop frames

### ISSUE THREAD

**Issue by h20534** [TwitchedApp/Twitched#29]
### Description
60fps streams freeze, drop frames

### Steps to Reproduce
1. Select any 60fps steam (easiest one to usually find is Ninja's fortnite streams)
2. Playback will be smooth until frames are dropped, sound continues on, video syncs back up with audio a few seconds later

...

**Expected behavior:** Stream continues smooth at 60fps

**Actual behavior:** Stream appears to freeze for a few seconds at a time (not buffering)

**Roku Model:** Streaming Stick 3600

**Roku Firmware Version:** 8.0

**Twitched Version:** Latest version from Roku Store (downloaded 6/25/18)

### Additional Information
I think this might be related to issue #23 I see the "fix" was applied to the 3800 stick (limiting streams to 30fps) but maybe not to the 3600 sticks?

**Comment by h20534** [comment]
Hey @rolandoislas , I see it's been marked as "fix applied" but is this an actual fix, or is it just limiting streams to 30fps on the 3600 stick? Also, is this fix live in the current app, or do we have to wait for an update?

Thanks! Love the app!

**Comment by rolandoislas** [comment]
All streams have been limited to 30 FPS on the Roku model 3600X. This is live on v1.4 and v1.5, but "Local Stream Fetching" will need to be disabled in v1.5's settings.
