### ISSUE TITLE
-3 error on some streams

### ISSUE THREAD

**Issue by R-izz** [TwitchedApp/Twitched#30]
### Description
When trying to load some streams I get the error code -3

### Steps to Reproduce
1. launch twtiched
2. Load Ninja's stream

...

**Expected behavior:** Load the stream

**Actual behavior:** -3 error notification
**Roku Model:** Unknown

**Roku Firmware Version:** Unknown

**Twitched Version:** Current

### Additional Information
[Any other information related to the problem]

**Comment by rolandoislas** [comment]
Does the app have a liked Twitch account?

**Comment by R-izz** [comment]
No, is that the problem?

**Comment by rolandoislas** [comment]
It is a workaround until v1.5 is released.

**Comment by rolandoislas** [comment]
A server update has been released that may resolve the issue.
