### ISSUE TITLE
Stream stuttering

### ISSUE THREAD

**Issue by cyberoptics22** [TwitchedApp/Twitched#33]
### Description
Streams will stutter multiple times per second on any quaility above 480p

### Steps to Reproduce
1. Set quality to anything above 480p
2. Watch stream, specifically Ninja, iiJericoii, joshOG

...

**Expected behavior:** smooth stream playback

**Actual behavior:** constant stuttering, no buffering or other connection issues

**Roku Model:** 3910RW - Roku Express+

**Roku Firmware Version:** 8.1.0 build 4137-51 

**Twitched Version:** 1.5

### Additional Information
Seems to be every stream I’ve tried, changing quality to 480p or lower resolves issue. Started happening within the last 2 weeks, prior to that streams were perfect. Using Twitched app not Twitched zero.

**Comment by rolandoislas** [comment]
See #31.

**Comment by rolandoislas** [comment]
Is this also happening at the 1080p resoultion?

**Comment by cyberoptics22** [comment]
Yes it is happening at 1080p as well
