### ISSUE TITLE
API Error - Twitch API Changes

### ISSUE THREAD

**Issue by Fwamper** [TwitchedApp/Twitched#40]
I haven't had this problem before but just today in the last hour or so I try to put on any stream, and nothing is even able to load. Tried logging off, re-installing, re-connecting to internet, and nothing has worked so far.

**Comment by Paikage** [comment]
I'm having the same issue, and have gone through the same steps to try to troubleshoot it with no luck.

**Comment by meachamsc** [comment]
Exact same issue here too.  Roku throws error as follows: "Failed to connect to the API server. Error code 1005."

**Comment by rolandoislas** [comment]
An update has been release that fixes this issue. There may be other API changes of which we are not aware, so this issue will remain open for API error related reports.
