### ISSUE TITLE
Interrupted Video on Roku

### ISSUE THREAD

**Issue by DSR999** [TwitchedApp/Twitched#6]
### Description
Video stream cuts out every 3 seconds.

### Steps to Reproduce
1. Open Roku. Play Stream.
2. [Second step]

...

**Expected behavior:** [What was supposed to happen]
Uninterrupted stream.
**Actual behavior:** [What actually happened]
Interrupted stream.
**Roku Model:** [Model]
4630x - 
**Roku Firmware Version:** [Firmware version] 
8.01 - b~ 4042-29
**Twitched Version:** [Version number]
1. 1 - B~ 1745
### Additional Information
Alternates between stream cut out and steady stream with slowed down audio after a while of either occurring.  Already restarted streamer and streamed from browser in same subnet.

**Comment by rolandoislas** [comment]
Related to #4 and #5.

**Comment by rolandoislas** [comment]
I'm closing this to keep it in one thread, #4.
