### ISSUE TITLE
VODs don't seem to work when a channel is currently offline

### ISSUE THREAD

**Issue by Squeakychu** [TwitchedApp/Twitched#7]
### Description
When selecting a past video from a channel that's currently offline, instead of playing the video, the error "The stream is offline" is displayed instead. 

### Steps to Reproduce
1. Type a channel/video in the search field
2. Go to any channel or video that is currently not live.
3. Go to the Videos option on the stream menu.
4. Select any past broadcasts.

...

**Expected behavior:** The past broadcast should play as normal, with the option to fast-forward/rewind the video.

**Actual behavior:** The error message, "The stream is offline" displays instead, and does not play the selected video.

**Roku Model:** 3800X

**Roku Firmware Version:** 8.0.1 build 4042-55

**Twitched Version:** 1.1 build 1745

### Additional Information
This problem does not seem to occur with channels that are currently live.

**Comment by nadeemc** [comment]
+1

**Comment by rolandoislas** [comment]
A workaround until version 1.2 is released is to cast VODs via the [browser extension](https://www.twitched.org/extension) or [Android app](https://www.twitched.org/app).

**Comment by nadeemc** [comment]
Thank you, the browser extension with Google Chrome did the trick for me! One way to improve the casting would be to resume from the point in the VOD I am currently at, but that is not a big deal since I was able to fast-forward the VOD on the Roku after it started casting.

Thanks Rolando!

**Comment by rolandoislas** [comment]
Fixed in v1.2
