### ISSUE TITLE
Video not playing on Insignia Roku TV

### ISSUE THREAD

**Issue by rabe5775** [TwitchedApp/Twitched#8]
### Description
I just purchased this on my Insignia Roku TV and was trying to watch an Overwatch stream. I tried a couple different channels and they all produced the same result. The bar showing load progress is full, but the video is not playing. It is just showing a black screen

### Steps to Reproduce
1. Play any live streaming channel

...

**Expected behavior:** Video to play

**Actual behavior:** Retrieving status bar showing full, but not actually playing the stream

**Roku Model:** Insignia Roku TV

**Roku Firmware Version:** [Firmware version] 

**Twitched Version:** [Version number]

### Additional Information
[Any other information related to the problem]

**Comment by rolandoislas** [comment]
What version of Twitched and Roku OS is the Roku running? The Twitched version can be found by pressing the options key while Twitched is selected on the application grid home screen. The Roku OS and model information is available in the settings.

If the Twitched version is below v1.1.1175, a [manual system update](https://support.roku.com/article/208755668-how-to-update-the-software-on-your-roku-streaming-device) may be needed.

**Comment by rolandoislas** [comment]
Fix applied.
